---
credentials:
  description: "An array of credientails"
  required: true
  type: "array"
  items:
    type: "object"
    required: true
    properties:
      username:
        description: "Username to connect to devices"
        type: "string"
        required: true
      password:
        description: "Password to connect to devices"
        type: "string"
        required: true

bgpsensordevices:
  description: "The array of devices"
  required: true
  type: "array"
  items:
    type: "object"
    required: true
    properties:
      driver:
        description: "Driver for the device"
        type: "string"
        required: true
      hostname:
        description: "Hostname for the device"
        type: "string"
        required: true
      username:
        description: "Username for the device"
        type: "string"
        required: true
      password:
        description: "Password for the device"
        type: "string"
        required: true
        secret: true
      port:
        description: "Port for the device"
        type: "integer"
        required: true
