---
name: "get_bgp_config"
runner_type: "python-script"
description: "Get BGP configuration from a device using NAPALM."
enabled: true
entry_point: "get_bgp_config.py"
parameters:
    hostname:
        type: "string"
        description: "The hostname of the device to connect to. Driver must be specified if hostname is not in configuration. Hostname without FQDN can be given if device is in configuration."
        required: true
        position: 0
    driver:
        type: "string"
        description: "Device driver name for connecting to device, see https://napalm.readthedocs.io/en/latest/support/index.html for list."
        required: false
        position: 1
    port:
        type: "string"
        description: "port for accessing device"
        required: false
        position: 2
    credentials:
        type: "string"
        description: "The credentials group which contains the username and password to log in"
        required: false
        position: 3
    group:
        type: "string"
        description: "Restrict configuration to this BGP neighbor/Peer group"
        required: false
        position: 4
    neighbor:
        type: "string"
        description: "Restrict configuration to this BGP neighbor"
        required: false
        position: 5
    htmlout:
        type: "boolean"
        description: "In addition to the normal output also includes html output."
        required: false
        position: 6
