---
name: "get_config"
runner_type: "python-script"
description: "Get configuration from the device using NAPALM."
enabled: true
entry_point: "get_config.py"
parameters:
    driver:
        type: "string"
        description: "device type"
        required: true
        position: 0
    hostname:
        type: "string"
        description: "The hostname of the device to which you wish to post a configuration"
        required: true
        position: 1
    port:
        type: "string"
        description: "port for accessing device"
        required: false
        position: 2
    credentials:
        type: "string"
        description: "The credentials group which contains the username and password to log in"
        required: true
        position: 3
    retrieve:
        type: "string"
        description: "Configuration section to be retrieved"
        required: false
        position: 4
