---
  name: "configured_device"
  enabled: true
  description: "Webhook which handles when a device has been configured"

  trigger:
    type: "core.st2.webhook"
    parameters:
      url: "napalm_conf_device"

  criteria:
    # Don't trigger only when a commit requested wait for commit complete on JunOS
    trigger.body.message:
      type: "ncontains"
      pattern : "requested 'commit' operation"

  action:
    ref: napalm.configured_device_chain
    parameters:
      hostname: "{{trigger.body.logsource}}"
      message: "{{trigger.body.message}}"
