---
  name: "configured_device"
  enabled: true
  description: "Webhook which handles when a device has been configured and changes commited"

  trigger:
    type: "core.st2.webhook"
    parameters:
      url: "napalm_conf_device"

  criteria: {}

  action:
    ref: napalm.configured_device_chain
    parameters:
      hostname: "{{trigger.body.logsource}}"
      message: "{{trigger.body.message}}"
